<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2YpUFZR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2YpUFZR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2YpUFZR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2YpUFZR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2YpUFZR\App_KernelDevDebugContainer([
    'container.build_hash' => '2YpUFZR',
    'container.build_id' => '1ffff71d',
    'container.build_time' => 1697404045,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2YpUFZR');
